[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x", "openssl"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "pnpm i --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm --filter=api build"]

[start]
cmd = "cd apps/api && pnpm start"
